version: '3.8'

services:
  api:
    build: .
    container_name: husna-api
    restart: always
    # Exposing the port to the external network
    expose:
      - "3005"
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
    networks:
      - shared_caddy_network

networks:
  shared_caddy_network:
    external: true
    name: app_default
